# Generated by Django 4.1.7 on 2023-03-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='days',
        ),
        migrations.AlterField(
            model_name='day',
            name='activities',
            field=models.ManyToManyField(blank=True, to='main_app.activity'),
        ),
    ]
