# Generated by Django 4.1.7 on 2023-03-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_trip_days_alter_day_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='day',
            name='flight',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='day',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='day',
            name='lodging',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='transport',
            field=models.CharField(choices=[('W', 'Walk'), ('B', 'Bike'), ('D', 'Drive'), ('T', 'Train'), ('F', 'Fly')], default='D', max_length=1),
        ),
    ]
