# Generated by Django 4.1.7 on 2023-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_activity_inout_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='inout',
            field=models.CharField(choices=[('I', 'Inside'), ('O', 'Outside')], default='I', max_length=1),
        ),
    ]
