# Generated by Django 4.1.7 on 2023-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_activity_inout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='inout',
            field=models.CharField(choices=[('I', 'Inside'), ('O', 'Outside')], default='I', max_length=10),
        ),
    ]
