# Generated by Django 4.1.7 on 2023-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_activity_description_alter_activity_inout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='Morning', max_length=1),
        ),
    ]
