# Generated by Django 4.1.7 on 2023-03-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_activity_description_alter_activity_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='inout',
        ),
    ]
