# Generated by Django 4.1.7 on 2023-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_activity_inout_alter_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(),
        ),
    ]
